name = "offer-tracker"
compatibility_date = "2025-03-31"
main = "./dist/_worker.js"

[site]
bucket = "./dist"

[build]
command = "npm run build"
upload.format = "directory"

[assets]
directory = "./dist" 